version: '3'

services:
  nginx:
    build:
      context: ./docker
      dockerfile: nginx.docker
      args:
        - "USER_ID=${USER_ID}"
        - "GROUP_ID=${GROUP_ID}"
    volumes:
      - ./:/var/www
    ports:
      - "${APP_PORT}:80"
    links:
      - php-fpm
  php-fpm:
    build:
      context: ./docker
      dockerfile: php-fpm.docker
      args:
        - "USER_ID=${USER_ID}"
        - "GROUP_ID=${GROUP_ID}"
    environment:
      PHP_IDE_CONFIG: serverName=TaskManager
    volumes:
      - ./:/var/www
    links:
      - db
      - redis
  php-cli:
    build:
      context: ./docker
      dockerfile: php-cli.docker
      args:
        - "USER_ID=${USER_ID}"
        - "GROUP_ID=${GROUP_ID}"
    volumes:
      - ./:/var/www
    links:
      - db
      - redis
    tty: true
  db:
    image: mysql:5.7
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${DB_DATABASE}"
      - "MYSQL_USER=${DB_USERNAME}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
    volumes:
      - db:/var/lib/mysql
    ports:
      - "33061:3306"
  redis:
    image: redis
    hostname: redis
  node:
    build:
      context: ./docker
      dockerfile: node.docker
    volumes:
      - ./:/var/www
    tty: true
  sheduler:
    build:
      context: ./docker
      dockerfile: sheduler.docker
    volumes:
      - ./:/var/www
    entrypoint:
      - /docker-entrypoint.sh
    links:
      - db
    depends_on:
      - php-fpm
volumes:
  db:
